sprintf(buffer,"**System used for compilation:\n");
output_string(buffer);
sprintf(buffer,"**Linux linaro-alip 3.0.36-t2f2optimized+ #1 PREEMPT Mon Jul 30 11:48:07 CEST 20\n");
output_string(buffer);
sprintf(buffer,"**C compiler: gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) \n");
output_string(buffer);
sprintf(buffer,"**libc: libc-2.15.so\n");
output_string(buffer);
sprintf(buffer,"**Date of compilation: Mon Jul 30 10:25:04 UTC 2012\n");
output_string(buffer);
