#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/cgroup-lite" ]; then
	if [ ! -e "/etc/init/cgroup-lite.conf" ]; then
		update-rc.d cgroup-lite defaults >/dev/null
	fi
	invoke-rc.d cgroup-lite start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f cgroup-lite remove >/dev/null || exit $?
# End automatically added section
