#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/modemmanager" ]; then
	if [ ! -e "/etc/init/modemmanager.conf" ]; then
		update-rc.d modemmanager defaults >/dev/null
	fi
	invoke-rc.d modemmanager start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f modemmanager remove >/dev/null || exit $?
# End automatically added section
